service: notify

provider:
  name: aws
  runtime: nodejs14.x

functions:
  rateHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)
